<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php //echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink()
										        ->prependStylesheet($this->basePath() . '/style/typography.css')
										        ->prependStylesheet($this->basePath() . '/style/root.css')
										        ->prependStylesheet($this->basePath() . '/style/reset.css')
		?>
        <!-- Scripts -->



<style>#stats{display:block;}</style>
    </head>
    <body>

<?php
// module/projet/view/projet/projet/add.phtml:

$title = "Ajout d'un nouveau projet";
$this->headTitle($title);
?>





                    <!-- start page title -->
                    <div class="page-title" style=" width:520px;">
                        <div class="in">
                                <div class="titlebar">	<h2><?php echo $this->escapeHtml($title); ?></h2></div>


                                <div class="clear"></div>
                        </div>
                    </div>
                    <!-- end page title -->

                    <!-- START CONTENT -->
                    <div class="content" style=" width:520px;">
                    <!-- START FORMULAIRE -->

                        	<div class="simplebox grid740" style="z-index: 720; width:520px;">
                        	<?php if(!$this->save){?>
                            	<div class="titleh" style="z-index: 710; ">
                                	<h3>Formulaire d'ajout</h3>
                                </div>
                                <div class="body" style="z-index: 690;">
								<?php
									$form = $this->form;
									$form->setAttribute('action', $this->url('projet/add'));
									$form->prepare();
                                ?>
                                  <?php echo $this->form()->openTag($form); ?>
                                  	<div class="st-form-line" style="z-index: 680;">
                                    	<span class="st-labeltext">Nom</span>
                                        <?php  echo $this->formRow($form->get('nomprojet')); ?>
                                    <div class="clear" style="z-index: 670;"></div>
                                    </div>


                                    <div class="button-box" style="z-index: 620;">
                                   	  <?php echo $this->formSubmit($form->get('submit')); ?>
                                    </div>

                                  <?php echo $this->form()->closeTag(); ?>

                                </div>
                                 <?php }?>
                                <?php if($this->save){?>
                                <div class="albox succesbox">
                                	<b>Succ&egrave;s :</b> Nouveau Projet ajout&eacute; avec Succ&egrave;s.
                                	 <div class="shortcuts-icons " style="margin-right:30px" >
                            	<a class="shortcut tips" href="<?php echo $this->basePath(); ?>/projet/add"  title="Ajouter un nouveau projet"><img src="<?php echo $this->basePath(); ?>/img/icons/shortcut/plus.png" width="25" height="25" alt="Ajouter un nouveau projet" /></a>
                                </div>
                                </div>
                                <?php }?>
                            </div>


                        <!-- END FORMULAIRE -->

                    </div>
                    <!-- END CONTENT -->





    </body>
</html>





