<?php
// module/User/view/user/user/add.phtml:

$title = 'Gestion des tests';
$this->headTitle($title);
?>

<div id="page">



                    <!-- start page title -->
                    <div class="page-title">
                        <div class="in">
                                <div class="titlebar">	<h2><?php echo $this->escapeHtml($title); ?></h2>	<p>This is a quick overview of some features</p></div>

                                <div class="shortcuts-icons">
                                    <a class="shortcut tips" href="<?php echo $this->url('test'); ?>" title="Rafraichir les donn&eacute;es"><img src="<?php echo $this->basePath(); ?>/img/icons/shortcut/refresh.png" width="25" height="25" alt="icon" /></a>
                                    <a class="shortcut tips" href="<?php echo $this->url('test'); ?>" title="Liste des utilisateurs"><img src="<?php echo $this->basePath(); ?>/img/icons/shortcut/dashboard.png" width="25" height="25" alt="icon" /></a>
                                    <a class="shortcut tips" href="<?php echo $this->url('test/add'); ?>" title="Ajouter un utilistauer"><img src="<?php echo $this->basePath(); ?>/img/icons/shortcut/plus.png" width="25" height="25" alt="icon" /></a>
                                    <a class="shortcut tips" href="#" title="Chercher"><img src="<?php echo $this->basePath(); ?>/img/icons/shortcut/search.png" width="25" height="25" alt="icon" /></a>
                                </div>

                                <div class="clear"></div>
                        </div>
                    </div>
                    <!-- end page title -->

                    <!-- START CONTENT -->
                    <div class="content">
                    <!-- START FORMULAIRE -->

                        	<div class="simplebox grid740" style="z-index: 720;">
                            	<div class="titleh" style="z-index: 710;">
                                	<h3>Modification d'un Test</h3>
                                    <div class="shortcuts-icons" style="z-index: 700;">	<a href="#" class="shortcut tips" original-title="This is Simple Form"><img width="25" height="25" alt="icon" src="<?php echo $this->basePath(); ?>/img/icons/shortcut/question.png"></a>	</div>
                                </div>
                                <div class="body" style="z-index: 690;">
								<?php
									$form = $this->form;
									$form->setAttribute('action', $this->url('editertest'));
									$form->prepare();

                                ?>
                                 <?php echo $this->form()->openTag($form); ?>
                                 <?php  echo $this->formRow($form->get('idtest')); ?>
                                  	<div class="st-form-line" style="z-index: 680;">
                                    	<span class="st-labeltext">Titre</span>
                                        <?php  echo $this->formRow($form->get('titretest')); ?>
                                    <div class="clear" style="z-index: 670;"></div>
                                    </div>

									<div class="st-form-line" style="z-index: 680;">
                                    	<span class="st-labeltext">Date de d&eacute;but</span>
                                        <script type="text/javascript">
											$(function() {
											$( "#datepicker" ).datepicker();
											});
										</script>
                                        <?php  echo $this->formRow($form->get('date')); ?>
                                    <div class="clear" style="z-index: 510;"></div>
                                    </div>
                                  	<div class="st-form-line" style="z-index: 660;">
                                    	<p class="st-labeltext">Description</p>
                                    <p style="margin-top:30px;"><?php  echo $this->formRow($form->get('description')); ?></p>
                                    <div class="clear" style="z-index: 670;"></div>
                                    </div>



                                    <div class="button-box" style="z-index: 460;">
                                   	  <?php echo $this->formSubmit($form->get('submit')); ?>
                                    </div>

                                  <?php echo $this->form()->closeTag(); ?>

                                </div>
                            </div>


                        <!-- END FORMULAIRE -->

                    </div>
                    <!-- END CONTENT -->

            </div>






