<?php
// module/User/view/user/user/index.phtml:

$title = 'Utilisateurs';
$this->headTitle($title);
?>

<div id="page">



                    <!-- start page title -->
                    <div class="page-title">
                        <div class="in">
                                <div class="titlebar">	<h2><?php echo $this->escapeHtml($title); ?></h2>	<p>This is a quick overview of some features</p></div>

                                <div class="shortcuts-icons">
                                    <a class="shortcut tips" href="<?php echo $this->url('user'); ?>" title="Rafraichir les donn&eacute;es"><img src="<?php echo $this->basePath(); ?>/img/icons/shortcut/refresh.png" width="25" height="25" alt="icon" /></a>
                                    <a class="shortcut tips" href="<?php echo $this->url('user'); ?>" title="Liste des utilisateurs"><img src="<?php echo $this->basePath(); ?>/img/icons/shortcut/dashboard.png" width="25" height="25" alt="icon" /></a>
                                    <a class="shortcut tips" href="<?php echo $this->url('user/add'); ?>" title="Ajouter un utilistauer"><img src="<?php echo $this->basePath(); ?>/img/icons/shortcut/plus.png" width="25" height="25" alt="icon" /></a>
                                    <a class="shortcut tips" href="#" title="Chercher"><img src="<?php echo $this->basePath(); ?>/img/icons/shortcut/search.png" width="25" height="25" alt="icon" /></a>
                                </div>

                                <div class="clear"></div>
                        </div>
                    </div>
                    <!-- end page title -->

                    <!-- START CONTENT -->
                    <div class="content">
                    <!-- START TABLE -->

                        <div class="simplebox grid740">

                        	<div class="titleh">
                            <h3>Liste des utilisateurs</h3>
                            <div class="shortcuts-icons " >
                            	<a class="shortcut tips" href="<?php echo $this->url('user/add'); ?>" title="Ajouter un utilistauer"><img src="<?php echo $this->basePath(); ?>/img/icons/shortcut/plus.png" width="25" height="25" alt="icon" /></a>
                                <a class="shortcut tips" href="#" title="Chercher"><img src="<?php echo $this->basePath(); ?>/img/icons/shortcut/search.png" width="25" height="25" alt="icon" /></a>
                                <a class="shortcut tips" href="<?php echo $this->url('user'); ?>" title="Rafraichir les donn&eacute;es"><img src="<?php echo $this->basePath(); ?>/img/icons/shortcut/refresh.png" width="25" height="25" alt="icon" /></a>
                            </div>
                            </div>
                            <!-- Start Data Tables Initialisation code -->
							<script type="text/javascript" charset="utf-8">
								$(document).ready(function() {
  								oTable = $('#myTable').dataTable({
    							"bJQueryUI": true,
    							"sPaginationType": "full_numbers"
    							});
  							} );
  						</script>
                            <!-- End Data Tables Initialisation code -->
                                <table id="myTable" cellpadding="0" cellspacing="0" border="0" class="display data-table" >
                                	<thead>
                                		<tr>
                                			<th>Nom et Pr&eacute;nom</th>
                                			<th>Email</th>
                                			<th>Pr&eacute;vil&egrave;ge</th>
                                			<th>Actions</th>
                                		</tr>
                                	</thead>

                                    <tbody>
                                     <?php foreach ($users as $liste) : ?>
										<tr class="gradeA">
											<td><?php echo $this->escapeHtml($liste->nom);?> <?php echo $this->escapeHtml($liste->prenom);?></td>
											<td><?php echo $this->escapeHtml($liste->email);?></td>
											<td><?php if($liste->previlege=='admin') echo 'Administrateur';?><?php if($liste->previlege=='user') echo 'Testeur';?></td>
											<td align="center">
												<a href="<?php echo $this->url('edit',
													array('id' => $liste->iduser));?>" class="tips" title="Modifier"><img src="<?php echo $this->basePath(); ?>/img/icons/sidemenu/file_edit.png" width="16" height="16" alt="icon" /></a>
												<a href="<?php echo $this->url('delete',
													array('id' => $liste->iduser));?>" class="tips" title="Supprimer"><img src="<?php echo $this->basePath(); ?>/img/icons/sidemenu/trash.png" width="16" height="16" alt="icon" /></a>
											</td>
										</tr>
									<?php endforeach; ?>
                                    </tbody>
                                </table>


                        </div>

                    </div>
                    <!-- END CONTENT -->

            </div>






