<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php //echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
       <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
										        ->prependStylesheet($this->basePath() . '/style/jquery-plugin-base.css')
										        ->prependStylesheet($this->basePath() . '/style/jquery-ui.css')
										        ->prependStylesheet($this->basePath() . '/style/typography.css')
										        ->prependStylesheet($this->basePath() . '/style/grid.css')
										        ->prependStylesheet($this->basePath() . '/style/root.css')
										        ->prependStylesheet($this->basePath() . '/style/reset.css')
		?>
      <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/media/js/jquery.dataTables.js', 'text/javascript')
                                      ->prependFile('https://www.google.com/jsapi')
                                      ->prependFile($this->basePath() . '/js/jquery.ui.accordion.js')
                                      ->prependFile($this->basePath() . '/js/jquery.ui.tabs.js')
                                      ->prependFile($this->basePath() . '/js/jquery.ui.datepicker.js')
                                      ->prependFile($this->basePath() . '/js/jquery.ui.slider.js')
                                      ->prependFile($this->basePath() . '/js/jquery.ui.widget.js')
                                      ->prependFile($this->basePath() . '/js/jquery.ui.mouse.js')
                                      ->prependFile($this->basePath() . '/js/jquery.ui.core.js')
                                      ->prependFile($this->basePath() . '/js/jquery.prettyPhoto.js')
                                      ->prependFile($this->basePath() . '/js/fullcalendar.min.js')
                                      ->prependFile($this->basePath() . '/js/popup.js')
                                      ->prependFile($this->basePath() . '/js/analytics.js')
                                      ->prependFile($this->basePath() . '/js/raphael.js')
                                      ->prependFile($this->basePath() . '/js/jquery.tablesorter.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.wysiwyg.js')
                                      ->prependFile($this->basePath() . '/js/jquery.uniform.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.tipsy.js')
                                      ->prependFile($this->basePath() . '/js/toogle.js')
                                      ->prependFile($this->basePath() . '/js/jquery-settings.js')
        							  ->prependFile($this->basePath() . '/media/js/jquery.js')?>



<style>#stats{display:block;}</style>
    </head>
    <body>
<?php

$title = 'Gestion des Versions';
$this->headTitle($title);
?>





                    <!-- start page title -->
                    <div class="page-title">
                        <div class="in">
                                <div class="titlebar">	<h2><?php echo $this->escapeHtml($title); ?></h2></div>


                        </div>
                    </div>
                    <!-- end page title -->

                    <!-- START CONTENT -->
                    <div class="content">
                    <!-- START TABLE -->


					<div class="simplebox grid740" style="z-index: 720; ">
                        	<?php if(!$this->save){?>
                            	<div class="titleh" style="z-index: 710; ">
                                	<h3>Modification de la version</h3>
                                </div>
                                <div class="body" style="z-index: 690;">
								<?php
									$form = $this->form;
									$form->setAttribute('action', $this->url('editerversion'));
									$form->prepare();
                                ?>
                                  <?php echo $this->form()->openTag($form); ?>
                                  <?php  echo $this->formRow($form->get('idversion')); ?>
                                 <?php  echo $this->formRow($form->get('idprojet')->setValue($this->idprojet)); ?>
                                  	<div class="st-form-line" style="z-index: 680;">
                                    	<span class="st-labeltext">Nom</span>
                                        <?php  echo $this->formRow($form->get('titreversion')); ?>
                                    <div class="clear" style="z-index: 670;"></div>
                                    </div>
									<div class="st-form-line" style="z-index: 1220;">
                                    	<span class="st-labeltext">Date de la version</span>
                                        <script type="text/javascript">
											$(function() {
											$( "#datepicker" ).datepicker();
											});
											</script>
                                        <?php  echo $this->formRow($form->get('date')); ?>
                                    <div class="clear" style="z-index: 650;"></div>
                                    </div>

                                    <div class="button-box" style="z-index: 620;">
                                   	  <?php echo $this->formSubmit($form->get('submit')); ?>
                                    </div>

                                  <?php echo $this->form()->closeTag(); ?>

                                </div>
                                 <?php }?>
                                <?php if($this->save){?>
                                <div class="albox succesbox">
                                	<b>Succ&egrave;s :</b> Version modifi&eacute;e avec Succ&egrave;s.
                                	 <div class="shortcuts-icons " style="margin-right:30px" >
                            	<a class="shortcut tips" href="<?php echo $this->url('version',
													array('id' => $this->idprojet));?>"  title="Ajouter une nouvelle version"><img src="<?php echo $this->basePath(); ?>/img/icons/shortcut/plus.png" width="25" height="25" alt="Ajouter une nouvelle version" /></a>
                                </div>
                                </div>
                                <?php }?>
                            </div>


		<!-- End Important prettyPhoto Js Codde -->
                        <div class="simplebox grid740">


		<script type="text/javascript" charset="utf-8">
								$(document).ready(function() {
  								oTable = $('#myTable').dataTable({
    							"bJQueryUI": true,
    							"sPaginationType": "full_numbers"
    							});
  							} );

  	  </script>
                      <div id="demo">
<table cellpadding="0" cellspacing="0" border="0" class="display data-table"  id="myTable" width="100%">
	<thead  >
		<tr>
             <th>ID</th>
             <th>Nom</th>
             <th>Date</th>
             <th>Actions</th>
        </tr>
	</thead>
	<tbody>
		 <?php foreach ($versions as $liste) : ?>
										<tr>
											<td><?php echo $this->escapeHtml($liste->idversion);?> </td>
											<td><?php echo $this->escapeHtml($liste->titreversion);?></td>
											<td><?php echo $this->escapeHtml($liste->date);?></td>
											<td align="center">
												<a href="<?php echo $this->url('editversion',
													array('id' => $liste->idversion));?>"   class="tips" title="Modifier"><img src="<?php echo $this->basePath(); ?>/img/icons/sidemenu/file_edit.png" width="16" height="16" alt="Modification de la version"  /></a>
												<a href="<?php echo $this->url('deleteversion',
													array('id' => $liste->idversion));?>" class="tips" title="Supprimer"><img src="<?php echo $this->basePath(); ?>/img/icons/sidemenu/trash.png" width="16" height="16" alt="icon" /></a>
											</td>
										</tr>
									<?php endforeach; ?>
	</tbody>
</table>
			</div>



						</div>

                    </div>
                    <!-- END CONTENT -->




    </body>
</html>



